language: c
script: make && make travis && ./sslsplit -V
matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install -qq libssl-dev libevent-dev check
    - os: linux
      compiler: clang
      before_install:
        - sudo apt-get install -qq libssl-dev libevent-dev check
    - os: osx
      before_install:
        - brew install openssl
        - brew install libevent
        - brew install check
